#! /bin/sh

bspc rule -a sun-awt-X11-XFramePeer floating=on
bspc rule -a org.gnome.Weather.Application floating=on
bspc rule -a qemu-system-arm_Linux_x86_64 floating=on

bspc config top_padding        20 
bspc config border_width       3 
bspc config window_gap         5 

bspc config normal_border_color "#EDD3DC"
bspc config focused_border_color "#586B89"

bspc config split_ratio         0.5
bspc config borderless_monocle  true 
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor -d i ii iii iv v vi vii viii ix x 

amixer -D pulse sset Master 70%
kbdFade in
numlockx on

compton -cC --config=.config/compton.conf &
feh --bg-fill ~/Pictures/Wallpapers/mtfuji.jpg

#source ~/.config/bar/barrc | bar -p -B "#BB2C3B4E" &
source ~/.config/bar/barrc | bar -f "-misc-dejavu sans mono-bold-r-normal--11-*-*-*-m-*-iso10646-1,-misc-fontawesome-medium-r-normal--0-0-0-0-p-0-iso10646-1" -p -B "#DD2C3B4E" | sh &
