#! /bin/sh

source ~/.config/bar/barrc | bar -p &

bspc config top_padding        15
bspc config border_width       3 
bspc config window_gap         10 

bspc config focused_border_color "#8BA3B2"
bspc config normal_border_color "#15374F"

bspc config split_ratio         0.52
bspc config borderless_monocle  true 
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

amixer -D pulse sset Master 60% &
asus-kbd-backlight max

feh --bg-fill ~/Pictures/Wallpapers/Senja_Norway.png
