#!/bin/bash
#config script for bar
#latest update 2015-07-13 2030

#Background for time box, selected workspace box, and other
#workspace text
DIMFORE=788BA9

#Used for selected workspace text and status labels
FORE=E6E6E6

RED=FF0000
WHITE=EDD3DC
BLACK=202020
GRAY=404040

#Do background
function B {
    echo "%{B#$2}$1%{B-}"
}

#Do foreground
function F {
	echo "%{F#$2}$1%{F-}"
}

#Convert hangul number to arabic
#There is probably a better way of doing this...
function HangulToArabic {
    case $1 in
        일)
            echo 1
            ;;
        이)
            echo 2
            ;;
        삼)
            echo 3
            ;;
        사)
            echo 4
            ;;
        오)
            echo 5
            ;;
        육)
            echo 6
            ;;
        칠)
            echo 7
            ;;
        팔)
            echo 8
            ;;
        구)
            echo 9
            ;;
        십 )
            echo 10
            ;;
    esac
}

#Get screen brightness
Backlight() {
    BACK=$(xbacklight -get | cut -d. -f1)
    echo -e "$(F '\uF0EB ' '00FF85')$(F $BACK $WHITE)"
}

#Echo buttons
#Currently just lock
Buttons() {
    echo -e "%{A:slimlock:}$(B ' '$(F '\uF023' '2C3B4E')' ' $DIMFORE)%{A}"
}

#Percentage battery remaining
Battery() {
    BATPERC=$(acpi --battery | cut -d, -f2 | sed 's/.$//' | tr -d '\n') 
    BATPERC_F=$(F $BATPERC $WHITE)
    BATSTR=$(F '\uF0E7' 'CCFF00')
    _20=20

    #printf '%s %s' $BATSTR $BATPERC_F
    echo -e $BATSTR $BATPERC_F
}

#Clock in YMD HHMM format
 Clock() {
    DATE=$(date "+%Y년 %m월 %d일 %H%M")
    echo "%{B#$DIMFORE} $DATE  %{B-}"
}

#Display active desktop and highlight desktops in use
Desktops() {
    printf "\uF31B"
    for i in 일 이 삼 사 오 육 칠 팔 구 십 
    do
        if [ $i != 일 ]; then
            printf '|'
        fi

		if [[ $i == "$(bspc query -D -d)" ]]; then
            printf '%s' "$(B " $(F $i $FORE) " $DIMFORE)$(F "%{U#ff404040}%{+u}" $GRAY)$(F '%{U-}%{-u}' $GRAY)"
        elif [[ -n "$(bspc query -W -d ^$(HangulToArabic $i))" ]]; then
            printf ' %s ' "$(F "%{U#ff404040}%{+u}" $GRAY)$(F $i $FORE)$(F '%{U-}%{-u}' $GRAY)"
		else
            printf ' %s ' "$(F '' $GRAY)$(F $i $DIMFORE)$(F '' $FORE)"
		fi
	done
}

#Get current ime and toggle en and kr
IME() {
    IME=$(ibus engine)
    NOT_IME="hangul"
    if [[ $IME == "xkb:us::eng" ]]; then
        IME="EN"
        NOT_IME="hangul"
    elif [[ $IME == "hangul" ]]; then
        IME="KR"
        NOT_IME="xkb\:us\:\:eng"
    else
        IME="??"
        NOT_IME="xkb\:us\:\:eng"
    fi

    echo -e "%{A:ibus engine $NOT_IME:}$(F '\uF11C ' 'FF66CC')$(F $IME $WHITE)%{A}"
}

#Display how much ram is available
Ram() {
    RAM=$(/usr/libexec/i3blocks/memory)
    echo -e "$(F '\uF0AE ' '8500FF')$(F $RAM $WHITE)"
}

#Display PC temperature in Celcius
Temperature() {
    TEMPERATURE=$(sensors coretemp-isa-0000 | awk '/Physical/ { print $4 }')
    echo -e "$(F '\uF06D ' 'DD0000')$(F $TEMPERATURE $WHITE)"
}

#Display current volume
Volume() {
    VOL=$(/usr/libexec/i3blocks/volume | cut -d% -f1)
    echo -e "%{A:amixer -D pulse sset Master toggle:}$(F '\uF028 ' '05AAFF')%{A}%{A:amixer -D pulse sset Master 10%-:}-%{A} $(F $VOL $WHITE) %{A:amixer -D pulse sset Master 10%+:}+%{A}"
}


#=======================MAIN DRIVER=======================
while true; do
    echo "%{l}%{F-}$(Clock)%{c}$(Desktops)%{r}$(Battery)  $(Volume)  $(Backlight)  $(Temperature)  $(Ram)  $(IME)  $(Buttons)" &
    sleep 0.5; 
done
