#!/bin/bash
#config script for bar
#latest update 2015-07-11 2321

function B {
    echo "%{B#$2}$1%{B-}"
}

function F {
	echo "%{F#$2}$1%{F-}"
}

#Background for time box, selected workspace box, and other
#workspace text
DIMFORE=788BA9

#Used for selected workspace text and status labels
FORE=E6E6E6

RED=FF0000
WHITE=EDD3DC
BLACK=202020
GRAY=404040

function romanToArabic {
    case $1 in
        i)
            echo 1
            ;;
        ii)
            echo 2
            ;;
        iii)
            echo 3
            ;;
        iv)
            echo 4
            ;;
        v)
            echo 5
            ;;
        vi)
            echo 6
            ;;
        vii)
            echo 7
            ;;
        viii)
            echo 8
            ;;
        ix)
            echo 9
            ;;
        x)
            echo 10
            ;;
    esac
}

#Get screen brightness
Backlight() {
    BACK=$(xbacklight -get | cut -d. -f1)
    echo -e "$(F '\uF0EB ' '00FF85')$(F $BACK $WHITE)"
}

#Percentage battery remaining
Battery() {
    BATPERC=$(acpi --battery | cut -d, -f2 | sed 's/.$//' | tr -d '\n') 
    BATPERC_F=$(F $BATPERC $WHITE)
    BATSTR=$(F '\uF0E7' 'CCFF00')
    _20=20

    #printf '%s %s' $BATSTR $BATPERC_F
    echo -e $BATSTR $BATPERC_F
}

#Clock in YMD HHMM format
 Clock() {
    DATE=$(date "+%Y-%m-%d %H%M")
    echo "%{B#$DIMFORE} $DATE  %{B-}"
}

#Display active desktop and highlight desktops in use
Desktops() {
    printf "\uF31B"
    for i in i ii iii iv v vi vii viii ix x 
    do
        if [ $i != i ]; then
            printf '|'
        fi

		if [[ $i == "$(bspc query -D -d)" ]]; then
            printf '%s' "%{A:$i:}$(B " $(F $i $FORE) " $DIMFORE)$(F "%{U#ff404040}%{+u}" $GRAY)$(F '%{U-}%{-u}' $GRAY)%{A}"
        elif [[ -n "$(bspc query -W -d ^$(romanToArabic $i))" ]]; then
            printf ' %s ' "%{A:$i:}$(F "%{U#ff404040}%{+u}" $GRAY)$(F $i $FORE)$(F '%{U-}%{-u}' $GRAY)%{A}"
		else
            printf ' %s ' "%{A:$i:}$(F '' $GRAY)$(F $i $DIMFORE)$(F '' $FORE)%{A}"
		fi
	done
}

#Display how much ram is available
Ram() {
    RAM=$(/usr/libexec/i3blocks/memory)
    SWAP=$(/usr/libexec/i3blocks/swap)
    echo -e "$(F '\uF0AE ' '8500FF')$(F $RAM $WHITE)$(F '  \uF0A0 ' 'FF8500')$(F $SWAP $WHITE)"
}

#Display PC temperature in Celcius
Temperature() {
    TEMPERATURE=$(sensors coretemp-isa-0000 | awk '/Physical/ { print $4 }')
    echo -e "$(F '\uF06D ' 'DD0000')$(F $TEMPERATURE $WHITE)"
}

#Display current volume
Volume() {
    VOL=$(/usr/libexec/i3blocks/volume | cut -d% -f1)
    echo -e "$(F '\uF028 ' '05AAFF')$(F $VOL $WHITE)"
}

#=======================MAIN DRIVER=======================
while true; do
    echo "%{l}%{F-}$(Clock)%{c}$(Desktops)%{r}$(Battery)  $(Volume)  $(Backlight)  $(Temperature)  $(Ram) " &
    sleep 0.5; 
done
